### PR TITLE
Update to @hapi/nes 12.x and @hapi/hapi 19.x

### PR DESCRIPTION
**Pull request by leobudima**

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing, would you mind to update?

**Comment by mcollina** [comment]
You might also want to update lab and code to the `@hapi` org.

**Comment by leobudima** [comment]
Hi @mcollina - thanks for looking at this - I updated the rest of dependencies, but I'm afraid it seems the reason for CI failing is that hapi removed support for Node v10 and now only works on v12, while the CI config tests 8 and 10...

**Comment by leobudima** [comment]
Thanks for your comments, @mcollina - CI was failing due to Hapi requiring Node v12...I updated .travis.yml to reflect!

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
